### ISSUE TITLE
Armstrong Number

### ISSUE THREAD

**Issue by harsh-dart** [harsh-dart/Harsh-Hacktoberfest2021#24]
Write program to check weather the number is armstrong number or not.

**Comment by SiddyDevelops** [comment]
Hey @harsh-dart I would like to work on this issue, please assign this to me.

**Comment by Kraken-ops** [comment]
Please assign me this , I want to contribute to this.

**Comment by SiddyDevelops** [comment]
Hey @harsh-dart I made a PR please review it.

**Comment by Kraken-ops** [comment]
Please review my PR.

**Comment by Abhishek07-0302** [comment]
Hey, I would like to contribute. Kindly assign me if available.
